Bookstore: create and remove books
mmatongo/bookstore pull request #2
Opened 2021-09-28 18:54 UTC by mmatongo

This PR adds the following changes and creates to the `dev-branch`

- Configure the Redux Store (`/src/redux/configureStore.js`) and importing the necessary methods from Redux:
  - Import `createStore`
  - Import `combineReducers`
  - Import `applyMiddleware` - To use some handy Redux middleware, like *redux logger*.
  - Import your `booksReducer`, which you are going to write in `/src/redux/books` directory.
- Write your book's actions and reducer (in `/src/redux/books/books.js`) using the [*ducks* pattern](https://github.com/erikras/ducks-modular-redux). 
- In your React component responsible for adding new books set the data inputs in the local React state (set *title* and *author*.
- In your React component responsible for removing books - implement that even by dispatching a corresponding action.
- Use the *redux-logger* to check if your application is working correctly - Open your browser's console and look for the logger messages. Upon every action dispatch, the logger will print:
  - **prev state** - the state of the whole Redux store before the current action was dispatched.
  - **action** - the action object that is being dispatched.
  - **next state** - the state of the Redux store after the current action was dispatched.
- Creates a `Store.js`
![src](https://user-images.githubusercontent.com/40806126/135148225-7991a55c-8eea-4765-a8e6-ebfb240d0e6b.png)

2021-09-28 20:21 UTC, EricMbouwe requested changes
Hi @mmatongo, 🖐

Good job so far! 👌
- Good readme
- Good PR
- Your app is working as expected

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-28 20:21 UTC, EricMbouwe commented on src/components/NewBook.js
> +  };
- [OPTIONAL] You can have this state and the onChange handler in one place for each. Just use an object to store the state of the form like:
```
const [state, setState] = useState({
   title: '',
   author: '',
   category: '',
})
```
And the onChange handler will take benefits of the `name` property that you have in your inputs and will be something like:
```
const handleChange = (e) => {
  const value = e.target.value
  setState({
    ...state,
    [evt.target.name]: value
  });
}
``

2021-09-28 20:21 UTC, EricMbouwe commented on src/components/Store.js
> +        category={book.category}
- [ ] Let's pass the book object itself as props instead of defining each attribute as a prop. This will make your code much easier since if you have a lot of property on your book object like for example 50, you will not have to list them all here.

2021-09-28 20:21 UTC, EricMbouwe commented on src/components/Books.js
> +  },
- [ ] I think that it should be better to have the name of this component file as singular since this represents a single book. Actually, it is plural `src/components/Books.js ` and it is confusing. Let's change it

2021-09-28 20:36 UTC, mmatongo commented on src/components/NewBook.js
> +  };
This is pretty interesting, let me look into implementing this, thank you for the feedback.

2021-09-28 21:58 UTC, mmatongo commented on src/components/Books.js
> +  },
Noted

2021-09-29 08:40 UTC, henatan99 commented on src/components/Books.js
> +  },
This issue is well addressed! :+1:

2021-09-29 08:47 UTC, henatan99 approved these changes
Hi @mmatongo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-29 08:47 UTC, merged

2021-09-29 08:48 UTC, mmatongo commented
> Hi @mmatongo ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 

Thank you